dist: trusty
sudo: required

language: go

os:
    - linux
    - osx

go:
    - 1.7.x
    - 1.8.x
    - master
env:
    - MODE=standard

matrix:
    allow_failures:
        - go: master
    include:
        - go: 1.8.x
          env: MODE=gopherjs
        - go: 1.8.x
          env: MODE=gopherjs
          os: osx
        - go: 1.8.x
          env: MODE=linter

install:
    - ./travis/install.sh $MODE

script:
    - ./travis/test.sh $MODE
