language: go

go:
    - 1.7

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install nodejs npm
    - npm install

install:
    # Normal Go deps
    - go get github.com/pborman/uuid github.com/dimfeld/httptreemux github.com/pkg/errors
    # GopherJS deps
    - go get -u github.com/gopherjs/gopherjs
    - go get -u -d -tags=js github.com/gopherjs/jsbuiltin
    # Linter
    - go get -u gopkg.in/alecthomas/gometalinter.v1
    - gometalinter.v1 --install

script:
    - diff -u <(echo -n) <(gofmt -d ./)
    - go install # to make gotype (run by gometalinter) happy
    - gometalinter.v1 --deadline=30s
    - go test $(go list ./... | grep -v pouchdb)
    - gopherjs test github.com/flimzy/kivik/test
